version: "3"
services:
  frontend:
    build: "./frontend"
    ports:
      - "3000:3000"
    env_file:
      - .frontend.env
    depends_on:
      - backend
  backend:
    build: "./backend"
    ports:
      - "8000:8000"
    env_file:
      - .backend.env
  db:
    image: postgres:11
    env_file:
      - .postgres.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
