name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'prueba-3/index.html'
env:
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
  
jobs:  
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to DockerHub              
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      working-directory: prueba-3
      
      run: |
        docker build -t $DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG .
        docker push $DOCKER_USER/$DOCKER_REPOSITORY:$IMAGE_TAG
        
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          envs: DOCKER_USER,DOCKER_REPOSITORY,IMAGE_TAG
          script: |
            # Stop and remove running container if exists
            docker stop $(echo $DOCKER_REPOSITORY) || true && docker rm $(echo $DOCKER_REPOSITORY) || true
            # Run a new container from a new image
            docker run -d \
            --restart always \
            --name $(echo $DOCKER_REPOSITORY) \
            -p 80:80 \
            $(echo $DOCKER_USER)/$(echo $DOCKER_REPOSITORY):$(echo $IMAGE_TAG)
